/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/message.pb-c.h"
void   auth_proto__init
                     (AuthProto         *message)
{
  static const AuthProto init_value = AUTH_PROTO__INIT;
  *message = init_value;
}
size_t auth_proto__get_packed_size
                     (const AuthProto *message)
{
  assert(message->base.descriptor == &auth_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth_proto__pack
                     (const AuthProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth_proto__pack_to_buffer
                     (const AuthProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AuthProto *
       auth_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AuthProto *)
     protobuf_c_message_unpack (&auth_proto__descriptor,
                                allocator, len, data);
}
void   auth_proto__free_unpacked
                     (AuthProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &auth_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query_header__init
                     (QueryHeader         *message)
{
  static const QueryHeader init_value = QUERY_HEADER__INIT;
  *message = init_value;
}
size_t query_header__get_packed_size
                     (const QueryHeader *message)
{
  assert(message->base.descriptor == &query_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_header__pack
                     (const QueryHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_header__pack_to_buffer
                     (const QueryHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryHeader *
       query_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryHeader *)
     protobuf_c_message_unpack (&query_header__descriptor,
                                allocator, len, data);
}
void   query_header__free_unpacked
                     (QueryHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &query_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query_proto__init
                     (QueryProto         *message)
{
  static const QueryProto init_value = QUERY_PROTO__INIT;
  *message = init_value;
}
size_t query_proto__get_packed_size
                     (const QueryProto *message)
{
  assert(message->base.descriptor == &query_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_proto__pack
                     (const QueryProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_proto__pack_to_buffer
                     (const QueryProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryProto *
       query_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryProto *)
     protobuf_c_message_unpack (&query_proto__descriptor,
                                allocator, len, data);
}
void   query_proto__free_unpacked
                     (QueryProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &query_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reply_header__init
                     (ReplyHeader         *message)
{
  static const ReplyHeader init_value = REPLY_HEADER__INIT;
  *message = init_value;
}
size_t reply_header__get_packed_size
                     (const ReplyHeader *message)
{
  assert(message->base.descriptor == &reply_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reply_header__pack
                     (const ReplyHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reply_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reply_header__pack_to_buffer
                     (const ReplyHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reply_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReplyHeader *
       reply_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReplyHeader *)
     protobuf_c_message_unpack (&reply_header__descriptor,
                                allocator, len, data);
}
void   reply_header__free_unpacked
                     (ReplyHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &reply_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reply_proto__init
                     (ReplyProto         *message)
{
  static const ReplyProto init_value = REPLY_PROTO__INIT;
  *message = init_value;
}
size_t reply_proto__get_packed_size
                     (const ReplyProto *message)
{
  assert(message->base.descriptor == &reply_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reply_proto__pack
                     (const ReplyProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reply_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reply_proto__pack_to_buffer
                     (const ReplyProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reply_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReplyProto *
       reply_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReplyProto *)
     protobuf_c_message_unpack (&reply_proto__descriptor,
                                allocator, len, data);
}
void   reply_proto__free_unpacked
                     (ReplyProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &reply_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor auth_proto__field_descriptors[3] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthProto, token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token_len",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AuthProto, token_len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "authorization",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(AuthProto, authorization),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth_proto__field_indices_by_name[] = {
  2,   /* field[2] = authorization */
  0,   /* field[0] = token */
  1,   /* field[1] = token_len */
};
static const ProtobufCIntRange auth_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor auth_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "auth_proto",
  "AuthProto",
  "AuthProto",
  "",
  sizeof(AuthProto),
  3,
  auth_proto__field_descriptors,
  auth_proto__field_indices_by_name,
  1,  auth_proto__number_ranges,
  (ProtobufCMessageInit) auth_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor query_header__field_descriptors[4] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(QueryHeader, host),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_agent",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(QueryHeader, user_agent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "authorization",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(QueryHeader, authorization),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(QueryHeader, content_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_header__field_indices_by_name[] = {
  2,   /* field[2] = authorization */
  3,   /* field[3] = content_type */
  0,   /* field[0] = host */
  1,   /* field[1] = user_agent */
};
static const ProtobufCIntRange query_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor query_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "query_header",
  "QueryHeader",
  "QueryHeader",
  "",
  sizeof(QueryHeader),
  4,
  query_header__field_descriptors,
  query_header__field_indices_by_name,
  1,  query_header__number_ranges,
  (ProtobufCMessageInit) query_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor query_proto__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(QueryProto, header),
    &query_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(QueryProto, body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_proto__field_indices_by_name[] = {
  1,   /* field[1] = body */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange query_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor query_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "query_proto",
  "QueryProto",
  "QueryProto",
  "",
  sizeof(QueryProto),
  2,
  query_proto__field_descriptors,
  query_proto__field_indices_by_name,
  1,  query_proto__number_ranges,
  (ProtobufCMessageInit) query_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reply_header__field_descriptors[2] =
{
  {
    "server",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReplyHeader, server),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReplyHeader, content_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reply_header__field_indices_by_name[] = {
  1,   /* field[1] = content_type */
  0,   /* field[0] = server */
};
static const ProtobufCIntRange reply_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor reply_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "reply_header",
  "ReplyHeader",
  "ReplyHeader",
  "",
  sizeof(ReplyHeader),
  2,
  reply_header__field_descriptors,
  reply_header__field_indices_by_name,
  1,  reply_header__number_ranges,
  (ProtobufCMessageInit) reply_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reply_proto__field_descriptors[4] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ReplyProto, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status_text",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReplyProto, status_text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "header",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ReplyProto, header),
    &reply_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ReplyProto, body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reply_proto__field_indices_by_name[] = {
  3,   /* field[3] = body */
  2,   /* field[2] = header */
  0,   /* field[0] = status */
  1,   /* field[1] = status_text */
};
static const ProtobufCIntRange reply_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor reply_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "reply_proto",
  "ReplyProto",
  "ReplyProto",
  "",
  sizeof(ReplyProto),
  4,
  reply_proto__field_descriptors,
  reply_proto__field_indices_by_name,
  1,  reply_proto__number_ranges,
  (ProtobufCMessageInit) reply_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
