/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: packet.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/packet.pb-c.h"
void   request_proto__init
                     (RequestProto         *message)
{
  static const RequestProto init_value = REQUEST_PROTO__INIT;
  *message = init_value;
}
size_t request_proto__get_packed_size
                     (const RequestProto *message)
{
  assert(message->base.descriptor == &request_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_proto__pack
                     (const RequestProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_proto__pack_to_buffer
                     (const RequestProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestProto *
       request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestProto *)
     protobuf_c_message_unpack (&request_proto__descriptor,
                                allocator, len, data);
}
void   request_proto__free_unpacked
                     (RequestProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_proto__init
                     (ResponseProto         *message)
{
  static const ResponseProto init_value = RESPONSE_PROTO__INIT;
  *message = init_value;
}
size_t response_proto__get_packed_size
                     (const ResponseProto *message)
{
  assert(message->base.descriptor == &response_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_proto__pack
                     (const ResponseProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_proto__pack_to_buffer
                     (const ResponseProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseProto *
       response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseProto *)
     protobuf_c_message_unpack (&response_proto__descriptor,
                                allocator, len, data);
}
void   response_proto__free_unpacked
                     (ResponseProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor request_proto__field_descriptors[4] =
{
  {
    "action",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RequestProto, action),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_enc",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(RequestProto, is_enc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RequestProto, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RequestProto, body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request_proto__field_indices_by_name[] = {
  0,   /* field[0] = action */
  3,   /* field[3] = body */
  1,   /* field[1] = is_enc */
  2,   /* field[2] = nonce */
};
static const ProtobufCIntRange request_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor request_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "request_proto",
  "RequestProto",
  "RequestProto",
  "",
  sizeof(RequestProto),
  4,
  request_proto__field_descriptors,
  request_proto__field_indices_by_name,
  1,  request_proto__number_ranges,
  (ProtobufCMessageInit) request_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_proto__field_descriptors[4] =
{
  {
    "is_enc",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ResponseProto, is_enc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ResponseProto, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ResponseProto, body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ResponseProto, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_proto__field_indices_by_name[] = {
  2,   /* field[2] = body */
  0,   /* field[0] = is_enc */
  1,   /* field[1] = nonce */
  3,   /* field[3] = signature */
};
static const ProtobufCIntRange response_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "response_proto",
  "ResponseProto",
  "ResponseProto",
  "",
  sizeof(ResponseProto),
  4,
  response_proto__field_descriptors,
  response_proto__field_indices_by_name,
  1,  response_proto__number_ranges,
  (ProtobufCMessageInit) response_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
