/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: user.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/user.pb-c.h"
void   user_db_proto__init
                     (UserDbProto         *message)
{
  static const UserDbProto init_value = USER_DB_PROTO__INIT;
  *message = init_value;
}
size_t user_db_proto__get_packed_size
                     (const UserDbProto *message)
{
  assert(message->base.descriptor == &user_db_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user_db_proto__pack
                     (const UserDbProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user_db_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user_db_proto__pack_to_buffer
                     (const UserDbProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user_db_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UserDbProto *
       user_db_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UserDbProto *)
     protobuf_c_message_unpack (&user_db_proto__descriptor,
                                allocator, len, data);
}
void   user_db_proto__free_unpacked
                     (UserDbProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &user_db_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   user_transit_proto__init
                     (UserTransitProto         *message)
{
  static const UserTransitProto init_value = USER_TRANSIT_PROTO__INIT;
  *message = init_value;
}
size_t user_transit_proto__get_packed_size
                     (const UserTransitProto *message)
{
  assert(message->base.descriptor == &user_transit_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user_transit_proto__pack
                     (const UserTransitProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user_transit_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user_transit_proto__pack_to_buffer
                     (const UserTransitProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user_transit_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UserTransitProto *
       user_transit_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UserTransitProto *)
     protobuf_c_message_unpack (&user_transit_proto__descriptor,
                                allocator, len, data);
}
void   user_transit_proto__free_unpacked
                     (UserTransitProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &user_transit_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor user_db_proto__field_descriptors[3] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UserDbProto, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UserDbProto, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "role",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(UserDbProto, n_role),
    offsetof(UserDbProto, role),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user_db_proto__field_indices_by_name[] = {
  1,   /* field[1] = password */
  2,   /* field[2] = role */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange user_db_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor user_db_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "user_db_proto",
  "UserDbProto",
  "UserDbProto",
  "",
  sizeof(UserDbProto),
  3,
  user_db_proto__field_descriptors,
  user_db_proto__field_indices_by_name,
  1,  user_db_proto__number_ranges,
  (ProtobufCMessageInit) user_db_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor user_transit_proto__field_descriptors[2] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UserTransitProto, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UserTransitProto, password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user_transit_proto__field_indices_by_name[] = {
  1,   /* field[1] = password */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange user_transit_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor user_transit_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "user_transit_proto",
  "UserTransitProto",
  "UserTransitProto",
  "",
  sizeof(UserTransitProto),
  2,
  user_transit_proto__field_descriptors,
  user_transit_proto__field_indices_by_name,
  1,  user_transit_proto__number_ranges,
  (ProtobufCMessageInit) user_transit_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
